=== SparkDevNetwork/Rock/Dev Tools/Schemas/theme.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://community.rockrms.com/schemas/2024-10-01/theme.json",
    "description": "RockRMS Theme Definition",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the theme that will be displayed in the UI."
        },
        "description": {
            "type": "string",
            "description": "Additional information about the theme."
        },
        "purpose": {
            "type": "string",
            "description": "The purpose of theme described by this file. This is used to determine which sites can use which themes. If not specified then it will be a 'web' theme.",
            "enum": [
                "web",
                "checkin"
            ]
        },
        "availableIconSets": {
            "type": "array",
            "description": "The font icon sets that are supported by this theme. If not specified then default values will be provided by Rock.",
            "items": {
                "type": "string",
                "enum": ["fontawesome", "tabler"]
            }
        },
        "fields": {
            "type": "array",
            "description": "The fields.",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/headingField"
                    },
                    {
                        "$ref": "#/definitions/spacerField"
                    },
                    {
                        "$ref": "#/definitions/literalField"
                    },
                    {
                        "$ref": "#/definitions/colorField"
                    },
                    {
                        "$ref": "#/definitions/textField"
                    },
                    {
                        "$ref": "#/definitions/imageField"
                    },
                    {
                        "$ref": "#/definitions/fileField"
                    },
                    {
                        "$ref": "#/definitions/switchField"
                    },
                    {
                        "$ref": "#/definitions/panelField"
                    }
                ]
            }
        }
    },
    "required": [
        "name"
    ],
    "definitions": {
        "variableName": {
            "type": "string",
            "description": "The display name of the variable."
        },
        "variable": {
            "type": "string",
            "description": "The CSS variable name to be generated for this value.",
            "pattern": "^[a-zA-Z0-9_-]+$"
        },
        "description": {
            "type": "string",
            "description": "The optional help text to display with the input control."
        },
        "literalField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that displays a single line of text. The value is written unformatted to the CSS file.",
                    "enum": [
                        "literal"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "default": {
                    "type": "string",
                    "description": "The default value to use for this variable."
                },
                "multiline": {
                    "type": "boolean",
                    "description": "Determines if the input box will display and accept multiple lines of text."
                },
                "width": {
                    "type": "string",
                    "description": "The suggested width of the input box.",
                    "enum": [
                        "sm",
                        "md",
                        "lg",
                        "xl",
                        "xxl"
                    ]
                }
            },
            "description": "A field that displays a single line of text.",
            "additionalProperties": false,
            "required": [
                "type",
                "name",
                "variable",
                "default"
            ]
        },
        "textField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that displays a single line of text. The value is wrapped in quotes and escaped when written to CSS.",
                    "enum": [
                        "text"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "default": {
                    "type": "string",
                    "description": "The default value to use for this variable."
                },
                "multiline": {
                    "type": "boolean",
                    "description": "Determines if the input box will display and accept multiple lines of text."
                },
                "width": {
                    "type": "string",
                    "description": "The suggested width of the input box.",
                    "enum": [
                        "sm",
                        "md",
                        "lg",
                        "xl",
                        "xxl"
                    ]
                }
            },
            "description": "A field that displays a single line of text.",
            "additionalProperties": false,
            "required": [
                "type",
                "name",
                "variable",
                "default"
            ]
        },
        "colorField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that will contain a CSS color value.",
                    "enum": [
                        "color"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "default": {
                    "type": "string",
                    "description": "The default value to use for this variable."
                }
            },
            "description": "A field that will contain a CSS color value.",
            "required": [
                "type",
                "name",
                "variable",
                "default"
            ]
        },
        "imageField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that will contain an image reference.",
                    "enum": [
                        "image"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "default": {
                    "type": "string",
                    "description": "The default value to use for this variable."
                }
            },
            "description": "A field that will contain an image reference.",
            "additionalProperties": false,
            "required": [
                "type",
                "name",
                "variable",
                "default"
            ]
        },
        "fileField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that will contain a file reference.",
                    "enum": [
                        "file"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "default": {
                    "type": "string",
                    "description": "The default value to use for this variable."
                }
            },
            "description": "A field that will contain a file reference.",
            "additionalProperties": false,
            "required": [
                "type",
                "name",
                "variable",
                "default"
            ]
        },
        "switchField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A field that will include one of two custom CSS content templates.",
                    "enum": [
                        "switch"
                    ]
                },
                "name": {
                    "$ref": "#/definitions/variableName"
                },
                "variable": {
                    "$ref": "#/definitions/variable"
                },
                "description": {
                    "$ref": "#/definitions/description"
                },
                "onContent": {
                    "type": "string",
                    "description": "The CSS content to include when the value is on."
                },
                "offContent": {
                    "type": "string",
                    "description": "The CSS content to include when the value is off."
                },
                "onValue": {
                    "type": "string",
                    "description": "The literal value to set the variable to when the value is on."
                },
                "offValue": {
                    "type": "string",
                    "description": "The literal value to set the variable to when the value is off."
                }
            },
            "description": "A field that will include one of two custom CSS content templates.",
            "required": [
                "type",
                "name",
                "variable"
            ]
        },
        "headingField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A section heading that can be used to group related fields together.",
                    "enum": [
                        "heading"
                    ]
                },
                "title": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The title to show in the heading."
                },
                "description": {
                    "type": "string",
                    "description": "The additional text to display below the heading."
                }
            },
            "description": "A section heading that can be used to group related fields together.",
            "additionalProperties": false,
            "required": [
                "type",
                "title"
            ]
        },
        "spacerField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "Inserts a small amount of whitespace between fields.",
                    "enum": [
                        "spacer"
                    ]
                }
            },
            "description": "Inserts a small amount of whitespace between fields.",
            "additionalProperties": false,
            "required": [
                "type"
            ]
        },
        "panelField": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "description": "A panel that will contain other fields.",
                    "enum": [
                        "panel"
                    ]
                },
                "title": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The text that will be displayed in the panel header."
                },
                "expanded": {
                    "type": "boolean",
                    "description": "If set then the panel will be expanded by default."
                },
                "fields": {
                    "type": "array",
                    "description": "The fields that will be displayed in this panel.",
                    "items": {
                        "oneOf": [
                            {
                                "$ref": "#/definitions/headingField"
                            },
                            {
                                "$ref": "#/definitions/spacerField"
                            },
                            {
                                "$ref": "#/definitions/literalField"
                            },
                            {
                                "$ref": "#/definitions/colorField"
                            },
                            {
                                "$ref": "#/definitions/textField"
                            },
                            {
                                "$ref": "#/definitions/imageField"
                            },
                            {
                                "$ref": "#/definitions/fileField"
                            },
                            {
                                "$ref": "#/definitions/switchField"
                            }
                        ]
                    }
                }
            },
            "description": "A panel that will contain other fields.",
            "additionalProperties": false,
            "required": [
                "type",
                "title"
            ]
        }
    }
}

=== SparkDevNetwork/Rock/RockWeb/Themes/NextGenCheckin/theme.json
{
    "$schema": "https://community.rockrms.com/schema/2024-10-01/theme.schema.json",
    "name": "NextGenCheckin",
    "description": "The default theme for the next generation check-in system.",
    "purpose": "checkin",
    "availableIconSets": ["fontawesome"],
    "fields": [
        {
            "type": "color",
            "name": "Primary Color",
            "variable": "color-primary",
            "description": "The primary color used to highlight screen elements, such as the main button.",
            "default": "#ee7725"
        },
        {
            "type": "image",
            "name": "Checkin Logo",
            "variable": "logo-image",
            "description": "The logo that wll be displayed throughout the Checkin.",
            "default": "~/Assets/Images/rock-logo-gray.svg"
        }
    ]
}

=== SparkDevNetwork/Rock/RockWeb/Themes/RockV2/Styles/theme.json
{
    "$schema": "https://community.rockrms.com/schema/2024-10-01/theme.schema.json",
    "name": "RockV2",
    "description": "The default theme for the RockV2.",
    "purpose": "web",
    "availableIconSets": ["fontawesome", "tabler"],
    "fields": [
        {
            "type": "color",
            "name": "Primary Color",
            "variable": "color-primary",
            "description": "The primary color used to highlight screen elements, such as the main button.",
            "default": "#ee7725"
        },
        {
            "type": "color",
            "name": "Interface Color Strongest",
            "variable": "color-interface-strongest",
            "description": "The strongest color used throughout the UI",
            "default": "#000000"
        },
        {
            "type": "color",
            "name": "Interface Color Stronger",
            "variable": "color-interface-stronger",
            "description": "A stronger color used throughout the UI",
            "default": "#1C1C1E"
        },
        {
            "type": "color",
            "name": "Interface Color Strong",
            "variable": "color-interface-strong",
            "description": "A strong color used throughout the UI",
            "default": "#5D5D6F"
        },
        {
            "type": "color",
            "name": "Interface Color Medium",
            "variable": "color-interface-medium",
            "description": "A medium color used throughout the UI",
            "default": "#8B8BA7"
        },
        {
            "type": "color",
            "name": "Interface Color Soft",
            "variable": "color-interface-soft",
            "description": "A soft color used throughout the UI",
            "default": "#D9D9E3"
        },
        {
            "type": "color",
            "name": "Interface Color Softer",
            "variable": "color-interface-softer",
            "description": "A softer color used throughout the UI",
            "default": "#E7E9EF"
        },
        {
            "type": "color",
            "name": "Interface Color Softest",
            "variable": "color-interface-softest",
            "description": "The softest color used throughout the UI",
            "default": "#FFFFFF"
        },
        {
            "type": "literal",
            "name": "XSmall Font Size",
            "variable": "font-size-xsmall",
            "description": "The font size for very small text",
            "default": "12px"
        },
        {
            "type": "literal",
            "name": "Small Font Size",
            "variable": "font-size-small",
            "description": "The font size for small text",
            "default": "14px"
        },
        {
            "type": "literal",
            "name": "Regular Font Size",
            "variable": "font-size-regular",
            "description": "The font size for regular text",
            "default": "16px"
        },
        {
            "type": "literal",
            "name": "H1 Font Size",
            "variable": "font-size-h1",
            "description": "The font size for h1 tag",
            "default": "44px"
        },
        {
            "type": "literal",
            "name": "H2 Font Size",
            "variable": "font-size-h2",
            "description": "The font size for h2 tag",
            "default": "36px"
        },
        {
            "type": "literal",
            "name": "H3 Font Size",
            "variable": "font-size-h3",
            "description": "The font size for h3 tag",
            "default": "28px"
        },
        {
            "type": "literal",
            "name": "H4 Font Size",
            "variable": "font-size-h4",
            "description": "The font size for h4 tag",
            "default": "22px"
        },
        {
            "type": "literal",
            "name": "H5 Font Size",
            "variable": "font-size-h5",
            "description": "The font size for h5 tag",
            "default": "18px"
        },
        {
            "type": "literal",
            "name": "H6 Font Size",
            "variable": "font-size-h6",
            "description": "The font size for h6 tag",
            "default": "16px"
        },
        {
            "type": "literal",
            "name": "Title Font Family",
            "variable": "font-family-title",
            "description": "The font family you wants your title to be",
            "default": "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'"
        },
        {
            "type": "literal",
            "name": "Body Font Family",
            "variable": "font-family-body",
            "description": "The font family you wants your body to be",
            "default": "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'"
        },
        {
            "type": "literal",
            "name": "Tiny Spacing",
            "variable": "spacing-tiny",
            "description": "The tiny spacing you want to set",
            "default": "4px"  
        },
        {
            "type": "literal",
            "name": "Tiny Spacing",
            "variable": "spacing-tiny",
            "description": "The tiny spacing you want to set",
            "default": "4px"
        },
        {
            "type": "literal",
            "name": "Small Spacing",
            "variable": "spacing-small",
            "description": "The small spacing you want to set",
            "default": "8px"
        },
        {
            "type": "literal",
            "name": "Medium Spacing",
            "variable": "spacing-medium",
            "description": "The medium spacing you want to set",
            "default": "16px"
        },
        {
            "type": "literal",
            "name": "Large Spacing",
            "variable": "spacing-large",
            "description": "The large spacing you want to set",
            "default": "24px"
        },
        {
            "type": "literal",
            "name": "XLarge Spacing",
            "variable": "spacing-xlarge",
            "description": "The extra-large spacing you want to set",
            "default": "48px"
        },
        {
            "type": "literal",
            "name": "Huge Spacing",
            "variable": "spacing-huge",
            "description": "The huge spacing you want to set",
            "default": "80px"
        },
        {
            "type": "literal",
            "name": "Lightening Percentage",
            "variable": "tint-white-percentage",
            "description": "The percentage of white added to create a tinted version for each application, i.e., --color-primary-tint",
            "default": "98%"
        },
        {
            "type": "literal",
            "name": "Darkening Percentage",
            "variable": "shade-black-percentage",
            "description": "The percentage of black added to create a shaded version for each application, i.e., --color-primary-shade ",
            "default": "15%"
        }
    ]
}
